# Generated by Django 3.2.6 on 2021-08-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('RUR', 'Russian Ruble')], default='RUR', max_length=3)),
                ('travelers', models.ManyToManyField(to='payments_logic.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments_logic.person')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments_logic.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments_logic.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments_logic.payment')),
            ],
        ),
    ]
